### ISSUE TITLE
sentryApiKey required even if using sentryBearerApiKey

### ISSUE THREAD

**Issue by jpaas** [dschmidt/ember-cli-deploy-sentry#38]
v 0.5.2

If I use the sentryBearerApiKey, I get an error that the sentryApiKey is required. If I set sentryApiKey with a garbage value, it works.

**Comment by duizendnegen** [comment]
Welcoming a PR, that would override the `configure` step in https://github.com/ember-cli-deploy/ember-cli-deploy-plugin/blob/master/index.js and still ensures that either `sentryApiKey` or `sentryBearerApiKey` is mandatory. If you need help implementing, I'd be happy to pitch in - same name on the Ember CLI Deploy channel in Slack.

**Comment by duizendnegen** [comment]
Fixed by https://github.com/dschmidt/ember-cli-deploy-sentry/pull/43

**Comment by mschinis** [comment]
@duizendnegen can you also publish the update on npm?

**Comment by duizendnegen** [comment]
As detailed in #43 - @dschmidt needs to publish the update on npm :)

**Comment by dschmidt** [comment]
Oh :) will do tonight and give Pepijn the needed rights to publish on npm
himself next time

Am 28.12.2017 4:52 nachm. schrieb "Pepijn Schoen" <notifications@github.com
>:

As detailed in #43
<https://github.com/dschmidt/ember-cli-deploy-sentry/pull/43> - @dschmidt
<https://github.com/dschmidt> needs to publish the update on npm :)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/dschmidt/ember-cli-deploy-sentry/issues/38#issuecomment-354309329>,
or mute the thread

**Comment by mschinis** [comment]
cool, thanks! 🎉
